source 'https://github.com/CocoaPods/Specs.git'

platform:ios,'8.0'
target 'greengreatwall' do
  pod 'JShare', '~> 1.7.0'
  pod 'JPush', '~> 3.2.6'
  pod 'AlipaySDK-iOS', '~> 15.5.9'
  pod 'WechatOpenSDK', '~> 1.8.6'
  pod 'AliyunOSSiOS', '~> 2.10.7'
  
  pod 'AFNetworking', '~> 3.1.0',:subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']
  pod 'SDWebImage', '~> 5.3.0'
  pod 'MJRefresh', '~> 3.1.15.3'
  pod 'Masonry', '~> 1.1.0'
  pod 'MJExtension', '~> 3.0.13'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'FMDB', '~> 2.7.5'
  pod 'SDCycleScrollView', '~> 1.75'
  pod 'YYCache', '~> 1.0.4'
  pod 'IQKeyboardManager', '~> 6.5.4'
  
  pod 'JSONModel', '~> 1.8.0'
  pod 'YYModel', '~> 1.0.4'
  
  pod 'BaiduMapKit', '~> 5.0.0'
  pod 'BMKLocationKit', '~> 1.8.0'
  
#  pod 'ReactiveObjC', '~> 3.1.1'
  
end
